# -*- coding: utf-8 -*-
"""WPL_2023_Scraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qgqHO8zNlxAs7bHGVTS3W_Pk59lVZsL9
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd


# Define the URL of the website to scrape
url = "https://sportstar.thehindu.com/cricket/wpl-auction-2023-top-sold-unsold-players-list-live-streaming-updates-wipl-womens-ipl/article66502635.ece"
data={'title': []}
# Send an HTTP GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the page using BeautifulSoup
    soup = BeautifulSoup(response.text, 'html.parser')
    #print(soup.prettify())
    #print(soup.find_all("div"))
    spans = soup.select("div.fact-element")
    #print(spans)
    for span in spans:
      print(span.string)
      data['title'].append(span.string)
df=pd.DataFrame.from_dict(data)
df.to_csv("data.csv")
df